### ISSUE TITLE
anes_functions.R 'twintables' throws an error

### ISSUE THREAD

**Issue by sjgenco** [czep/HTAD#1]
I'm trying to work with the new ANES 2020 dataset and as a first step I've been going thru your brilliant EDA example/code by replicating it in an RStudio notebook. I got everything loaded up and was able to successfully produce your first table ('Dataset version and unweighted counts'). However, an error popped up on the second table, which uses the `twintables` function in `anes_functions.R`. Here's your code under 'Sample mode':
```
t1 <- anes %>% count(sample_mode)
t2 <- anes %>%
  count(sample_mode, post_complete) %>%
  pivot_wider(names_from = post_complete, values_from = n)

k1 <- quicktable(t1, colnames = c("Sample mode", "N"), align = "lc")
k2 <- quicktable(t2, colnames = c("Sample mode", names(t2)[2:ncol(t2)]), align = "lcc")
twintables(k1, k2)
```
And here's the output I get:
```
Error in kables(list(k1 %>% kable_styling(full_width = FALSE, position = "float_left"),  : 
  could not find function "kables"
```
Here's the `twintables` function:
```
twintables <- function(k1, k2) {
  kables(
    list(
      k1 %>% kable_styling(full_width = FALSE, position = "float_left"),
      k2 %>% kable_styling(full_width = FALSE, position = "left")
    )
  )
}
```
It looks like that's the only place `kables` appears in `anes_functions.R`. I've tried running other tables in your article that use `twintables`, they get the same error.

I'm running R and RStudio in an anaconda virtual environment.
Anaconda Navigator version 2.0.3
R version 3.6.1
RStudio version 1.1.456
MacBook Pro 16, Big Sur 11.3.1

You've really built a great set of reusable tools here for wrangling such a complex dataset. Hope this is an easy fix (or I've just missed a step along the way somewhere). Thanks for all your work on this.

**Comment by sjgenco** [comment]
Solved it. I tracked down the function `kables()` and saw it was in the `knitr` package. Installed `knitr` and loaded the library and `twintables` now works as it should.

![t1](https://user-images.githubusercontent.com/19754884/119888928-ce6ff300-beea-11eb-887e-7e19df001271.jpg)

![t2](https://user-images.githubusercontent.com/19754884/119888972-de87d280-beea-11eb-80f7-bd0f96d70a3f.jpg)

**Comment by czep** [comment]
I'm glad to hear it worked. I should try to better document the dependencies, since there are nearly a dozen R packages involved!
